<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:req="http://schemas.hu.fnt.nl/berichten/request"
        xmlns:rsp="http://schemas.hu.fnt.nl/berichten/response"
        xmlns:tns="http://schemas.hu.fnt.nl/berichten/message"
        targetNamespace="http://schemas.hu.fnt.nl/berichten/message">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://schemas.hu.fnt.nl/berichten/request" schemaLocation="Request.xsd" />
            <xsd:import namespace="http://schemas.hu.fnt.nl/berichten/response" schemaLocation="Response.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="Request">
        <wsdl:part name="Request" element="req:Request" />
    </wsdl:message>

    <wsdl:message name="Response">
        <wsdl:part name="Response" element="rsp:Response" />
    </wsdl:message>

    <wsdl:portType name="WS-Interface">
        <wsdl:operation name="berekenTemperatuur">
            <wsdl:input message="tns:Request" />
            <wsdl:output message="tns:Response" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="WS-Binding" type="tns:WS-Interface">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="berekenTemperatuur">
            <soap:operation soapAction="" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="mijnService">
        <wsdl:port name="WS-Port" binding="tns:WS-Binding">
            <soap:address location="http://localhost:1337/services/TemperatuurService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>